language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t myproj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true myproj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Dockerreact-env-2"
  bucket_name: "elasticbeanstalk-ap-northeast-2-977176634452"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
